# Autogenerated test file
from fibonacci import fibonacci
def test_fibonacci_base_cases():
    assert fibonacci(0) == 0
    assert fibonacci(1) == 1

def test_fibonacci_small_numbers():
    assert fibonacci(2) == 1
    assert fibonacci(3) == 2
    assert fibonacci(4) == 3
    assert fibonacci(5) == 5

def test_fibonacci_larger_numbers():
    assert fibonacci(10) == 55
    assert fibonacci(15) == 610
    assert fibonacci(20) == 6765

def test_fibonacci_consistency():
    for i in range(2, 20):
        assert fibonacci(i) == fibonacci(i-1) + fibonacci(i-2)

def test_fibonacci_high_number():
    result = fibonacci(30)
    assert result == 832040

